# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CardComponent`.
# Please instead update this file by running `bin/tapioca dsl CardComponent`.


class CardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
