# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CopiableTextComponent`.
# Please instead update this file by running `bin/tapioca dsl CopiableTextComponent`.


class CopiableTextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
