# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FormContainerComponent`.
# Please instead update this file by running `bin/tapioca dsl FormContainerComponent`.


class FormContainerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
