# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NavbarComponent`.
# Please instead update this file by running `bin/tapioca dsl NavbarComponent`.


class NavbarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
