# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlanUsageComponent`.
# Please instead update this file by running `bin/tapioca dsl PlanUsageComponent`.


class PlanUsageComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
