# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlanDetailsComponent`.
# Please instead update this file by running `bin/tapioca dsl PlanDetailsComponent`.


class PlanDetailsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
