# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Ban_resp_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Ban_resp_v1`.


class Helium::PocMobile::Ban_resp_v1 < Google::Protobuf::AbstractMessage
  sig { params(timestamp_ms: T.nilable(Integer)).void }
  def initialize(timestamp_ms: nil); end

  sig { void }
  def clear_timestamp_ms; end

  sig { returns(Integer) }
  def timestamp_ms; end

  sig { params(value: Integer).void }
  def timestamp_ms=(value); end
end
