# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Boosted_hex`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Boosted_hex`.


class Helium::PocMobile::Boosted_hex < Google::Protobuf::AbstractMessage
  sig { params(location: T.nilable(Integer), multiplier: T.nilable(Integer)).void }
  def initialize(location: nil, multiplier: nil); end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_multiplier; end

  sig { returns(Integer) }
  def location; end

  sig { params(value: Integer).void }
  def location=(value); end

  sig { returns(Integer) }
  def multiplier; end

  sig { params(value: Integer).void }
  def multiplier=(value); end
end
