# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Carrier_id`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Carrier_id`.


module Helium::PocMobile::Carrier_id
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Carrier_id::carrier_0 = 0
Helium::PocMobile::Carrier_id::carrier_1 = 1
Helium::PocMobile::Carrier_id::carrier_2 = 2
Helium::PocMobile::Carrier_id::carrier_3 = 3
Helium::PocMobile::Carrier_id::carrier_4 = 4
Helium::PocMobile::Carrier_id::carrier_5 = 5
Helium::PocMobile::Carrier_id::carrier_6 = 6
Helium::PocMobile::Carrier_id::carrier_7 = 7
Helium::PocMobile::Carrier_id::carrier_8 = 8
Helium::PocMobile::Carrier_id::carrier_9 = 9
