# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Cell_type`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Cell_type`.


module Helium::PocMobile::Cell_type
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Cell_type::cell_type_none = 5
Helium::PocMobile::Cell_type::neutrino430 = 2
Helium::PocMobile::Cell_type::nova430i = 1
Helium::PocMobile::Cell_type::nova436h = 0
Helium::PocMobile::Cell_type::nova_generic_wifi_indoor = 6
Helium::PocMobile::Cell_type::nova_generic_wifi_outdoor = 7
Helium::PocMobile::Cell_type::sercomm_indoor = 3
Helium::PocMobile::Cell_type::sercomm_outdoor = 4
