# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Cell_heartbeat_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Cell_heartbeat_req_v1`.


class Helium::PocMobile::Cell_heartbeat_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      cbsd_category: T.nilable(String),
      cbsd_id: T.nilable(String),
      cell_id: T.nilable(Integer),
      coverage_object: T.nilable(String),
      hotspot_type: T.nilable(String),
      lat: T.nilable(Float),
      lon: T.nilable(Float),
      operation_mode: T.nilable(T::Boolean),
      pub_key: T.nilable(String),
      signature: T.nilable(String),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(cbsd_category: nil, cbsd_id: nil, cell_id: nil, coverage_object: nil, hotspot_type: nil, lat: nil, lon: nil, operation_mode: nil, pub_key: nil, signature: nil, timestamp: nil); end

  sig { returns(String) }
  def cbsd_category; end

  sig { params(value: String).void }
  def cbsd_category=(value); end

  sig { returns(String) }
  def cbsd_id; end

  sig { params(value: String).void }
  def cbsd_id=(value); end

  sig { returns(Integer) }
  def cell_id; end

  sig { params(value: Integer).void }
  def cell_id=(value); end

  sig { void }
  def clear_cbsd_category; end

  sig { void }
  def clear_cbsd_id; end

  sig { void }
  def clear_cell_id; end

  sig { void }
  def clear_coverage_object; end

  sig { void }
  def clear_hotspot_type; end

  sig { void }
  def clear_lat; end

  sig { void }
  def clear_lon; end

  sig { void }
  def clear_operation_mode; end

  sig { void }
  def clear_pub_key; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_timestamp; end

  sig { returns(String) }
  def coverage_object; end

  sig { params(value: String).void }
  def coverage_object=(value); end

  sig { returns(String) }
  def hotspot_type; end

  sig { params(value: String).void }
  def hotspot_type=(value); end

  sig { returns(Float) }
  def lat; end

  sig { params(value: Float).void }
  def lat=(value); end

  sig { returns(Float) }
  def lon; end

  sig { params(value: Float).void }
  def lon=(value); end

  sig { returns(T::Boolean) }
  def operation_mode; end

  sig { params(value: T::Boolean).void }
  def operation_mode=(value); end

  sig { returns(String) }
  def pub_key; end

  sig { params(value: String).void }
  def pub_key=(value); end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
