# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Coverage_object_validity`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Coverage_object_validity`.


module Helium::PocMobile::Coverage_object_validity
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Coverage_object_validity::coverage_object_validity_invalid_pub_key = 1
Helium::PocMobile::Coverage_object_validity::coverage_object_validity_valid = 0
