# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Data_transfer_radio_access_technology`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Data_transfer_radio_access_technology`.


module Helium::PocMobile::Data_transfer_radio_access_technology
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Data_transfer_radio_access_technology::EUTRAN = 5
Helium::PocMobile::Data_transfer_radio_access_technology::GAN = 3
Helium::PocMobile::Data_transfer_radio_access_technology::GERAN = 1
Helium::PocMobile::Data_transfer_radio_access_technology::HSPA_Evolution = 4
Helium::PocMobile::Data_transfer_radio_access_technology::UTRAN = 0
Helium::PocMobile::Data_transfer_radio_access_technology::WLAN = 2
