# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::File_info`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::File_info`.


class Helium::PocMobile::File_info < Google::Protobuf::AbstractMessage
  sig do
    params(
      file_type: T.nilable(T.any(Symbol, Integer)),
      key: T.nilable(String),
      size: T.nilable(Integer),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(file_type: nil, key: nil, size: nil, timestamp: nil); end

  sig { void }
  def clear_file_type; end

  sig { void }
  def clear_key; end

  sig { void }
  def clear_size; end

  sig { void }
  def clear_timestamp; end

  sig { returns(T.any(Symbol, Integer)) }
  def file_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def file_type=(value); end

  sig { returns(String) }
  def key; end

  sig { params(value: String).void }
  def key=(value); end

  sig { returns(Integer) }
  def size; end

  sig { params(value: Integer).void }
  def size=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
