# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Invalidated_radio_threshold_report_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Invalidated_radio_threshold_report_req_v1`.


class Helium::PocMobile::Invalidated_radio_threshold_report_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      carrier_pub_key: T.nilable(String),
      cbsd_id: T.nilable(String),
      hotspot_pubkey: T.nilable(String),
      reason: T.nilable(T.any(Symbol, Integer)),
      signature: T.nilable(String),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(carrier_pub_key: nil, cbsd_id: nil, hotspot_pubkey: nil, reason: nil, signature: nil, timestamp: nil); end

  sig { returns(String) }
  def carrier_pub_key; end

  sig { params(value: String).void }
  def carrier_pub_key=(value); end

  sig { returns(String) }
  def cbsd_id; end

  sig { params(value: String).void }
  def cbsd_id=(value); end

  sig { void }
  def clear_carrier_pub_key; end

  sig { void }
  def clear_cbsd_id; end

  sig { void }
  def clear_hotspot_pubkey; end

  sig { void }
  def clear_reason; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_timestamp; end

  sig { returns(String) }
  def hotspot_pubkey; end

  sig { params(value: String).void }
  def hotspot_pubkey=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def reason; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def reason=(value); end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
