# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Invalidated_radio_threshold_report_verification_status`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Invalidated_radio_threshold_report_verification_status`.


module Helium::PocMobile::Invalidated_radio_threshold_report_verification_status
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Invalidated_radio_threshold_report_verification_status::invalidated_threshold_report_status_invalid_carrier_key = 1
Helium::PocMobile::Invalidated_radio_threshold_report_verification_status::invalidated_threshold_report_status_valid = 0
