# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Mobile_reward_share`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Mobile_reward_share`.


class Helium::PocMobile::Mobile_reward_share < Google::Protobuf::AbstractMessage
  sig do
    params(
      end_period: T.nilable(Integer),
      gateway_reward: T.nilable(Helium::PocMobile::Gateway_reward),
      promotion_reward: T.nilable(Helium::PocMobile::Promotion_reward),
      radio_reward: T.nilable(Helium::PocMobile::Radio_reward),
      radio_reward_v2: T.nilable(Helium::PocMobile::Radio_reward_v2),
      service_provider_reward: T.nilable(Helium::PocMobile::Service_provider_reward),
      start_period: T.nilable(Integer),
      subscriber_reward: T.nilable(Helium::PocMobile::Subscriber_reward),
      unallocated_reward: T.nilable(Helium::PocMobile::Unallocated_reward)
    ).void
  end
  def initialize(end_period: nil, gateway_reward: nil, promotion_reward: nil, radio_reward: nil, radio_reward_v2: nil, service_provider_reward: nil, start_period: nil, subscriber_reward: nil, unallocated_reward: nil); end

  sig { void }
  def clear_end_period; end

  sig { void }
  def clear_gateway_reward; end

  sig { void }
  def clear_promotion_reward; end

  sig { void }
  def clear_radio_reward; end

  sig { void }
  def clear_radio_reward_v2; end

  sig { void }
  def clear_service_provider_reward; end

  sig { void }
  def clear_start_period; end

  sig { void }
  def clear_subscriber_reward; end

  sig { void }
  def clear_unallocated_reward; end

  sig { returns(Integer) }
  def end_period; end

  sig { params(value: Integer).void }
  def end_period=(value); end

  sig { returns(T.nilable(Helium::PocMobile::Gateway_reward)) }
  def gateway_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Gateway_reward)).void }
  def gateway_reward=(value); end

  sig { returns(Object) }
  def has_gateway_reward?; end

  sig { returns(Object) }
  def has_promotion_reward?; end

  sig { returns(Object) }
  def has_radio_reward?; end

  sig { returns(Object) }
  def has_radio_reward_v2?; end

  sig { returns(Object) }
  def has_service_provider_reward?; end

  sig { returns(Object) }
  def has_subscriber_reward?; end

  sig { returns(Object) }
  def has_unallocated_reward?; end

  sig { returns(T.nilable(Helium::PocMobile::Promotion_reward)) }
  def promotion_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Promotion_reward)).void }
  def promotion_reward=(value); end

  sig { returns(T.nilable(Helium::PocMobile::Radio_reward)) }
  def radio_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Radio_reward)).void }
  def radio_reward=(value); end

  sig { returns(T.nilable(Helium::PocMobile::Radio_reward_v2)) }
  def radio_reward_v2; end

  sig { params(value: T.nilable(Helium::PocMobile::Radio_reward_v2)).void }
  def radio_reward_v2=(value); end

  sig { returns(T.nilable(Symbol)) }
  def reward; end

  sig { returns(T.nilable(Helium::PocMobile::Service_provider_reward)) }
  def service_provider_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Service_provider_reward)).void }
  def service_provider_reward=(value); end

  sig { returns(Integer) }
  def start_period; end

  sig { params(value: Integer).void }
  def start_period=(value); end

  sig { returns(T.nilable(Helium::PocMobile::Subscriber_reward)) }
  def subscriber_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Subscriber_reward)).void }
  def subscriber_reward=(value); end

  sig { returns(T.nilable(Helium::PocMobile::Unallocated_reward)) }
  def unallocated_reward; end

  sig { params(value: T.nilable(Helium::PocMobile::Unallocated_reward)).void }
  def unallocated_reward=(value); end
end
