# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Oracle_boosting_report_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Oracle_boosting_report_v1`.


class Helium::PocMobile::Oracle_boosting_report_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      assignments: T.nilable(T.any(Google::Protobuf::RepeatedField[Helium::PocMobile::Oracle_boosting_hex_assignment], T::Array[Helium::PocMobile::Oracle_boosting_hex_assignment])),
      coverage_object: T.nilable(String),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(assignments: T.unsafe(nil), coverage_object: nil, timestamp: nil); end

  sig { returns(Google::Protobuf::RepeatedField[Helium::PocMobile::Oracle_boosting_hex_assignment]) }
  def assignments; end

  sig { params(value: Google::Protobuf::RepeatedField[Helium::PocMobile::Oracle_boosting_hex_assignment]).void }
  def assignments=(value); end

  sig { void }
  def clear_assignments; end

  sig { void }
  def clear_coverage_object; end

  sig { void }
  def clear_timestamp; end

  sig { returns(String) }
  def coverage_object; end

  sig { params(value: String).void }
  def coverage_object=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
