# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Oracle_boosting_hex_assignment`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Oracle_boosting_hex_assignment`.


class Helium::PocMobile::Oracle_boosting_hex_assignment < Google::Protobuf::AbstractMessage
  sig do
    params(
      assignment_multiplier: T.nilable(Integer),
      footfall: T.nilable(T.any(Symbol, Integer)),
      landtype: T.nilable(T.any(Symbol, Integer)),
      location: T.nilable(String),
      service_provider_override: T.nilable(T::Boolean),
      urbanized: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(assignment_multiplier: nil, footfall: nil, landtype: nil, location: nil, service_provider_override: nil, urbanized: nil); end

  sig { returns(Integer) }
  def assignment_multiplier; end

  sig { params(value: Integer).void }
  def assignment_multiplier=(value); end

  sig { void }
  def clear_assignment_multiplier; end

  sig { void }
  def clear_footfall; end

  sig { void }
  def clear_landtype; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_service_provider_override; end

  sig { void }
  def clear_urbanized; end

  sig { returns(T.any(Symbol, Integer)) }
  def footfall; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def footfall=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def landtype; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def landtype=(value); end

  sig { returns(String) }
  def location; end

  sig { params(value: String).void }
  def location=(value); end

  sig { returns(T::Boolean) }
  def service_provider_override; end

  sig { params(value: T::Boolean).void }
  def service_provider_override=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def urbanized; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def urbanized=(value); end
end
