# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Processed_files`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Processed_files`.


class Helium::PocMobile::Processed_files < Google::Protobuf::AbstractMessage
  sig do
    params(
      files: T.nilable(T.any(Google::Protobuf::RepeatedField[Helium::PocMobile::File_info], T::Array[Helium::PocMobile::File_info]))
    ).void
  end
  def initialize(files: T.unsafe(nil)); end

  sig { void }
  def clear_files; end

  sig { returns(Google::Protobuf::RepeatedField[Helium::PocMobile::File_info]) }
  def files; end

  sig { params(value: Google::Protobuf::RepeatedField[Helium::PocMobile::File_info]).void }
  def files=(value); end
end
