# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_threshold_report_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_threshold_report_req_v1`.


class Helium::PocMobile::Radio_threshold_report_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      bytes_threshold: T.nilable(Integer),
      carrier_pub_key: T.nilable(String),
      cbsd_id: T.nilable(String),
      hotspot_pubkey: T.nilable(String),
      signature: T.nilable(String),
      subscriber_threshold: T.nilable(Integer),
      threshold_timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(bytes_threshold: nil, carrier_pub_key: nil, cbsd_id: nil, hotspot_pubkey: nil, signature: nil, subscriber_threshold: nil, threshold_timestamp: nil); end

  sig { returns(Integer) }
  def bytes_threshold; end

  sig { params(value: Integer).void }
  def bytes_threshold=(value); end

  sig { returns(String) }
  def carrier_pub_key; end

  sig { params(value: String).void }
  def carrier_pub_key=(value); end

  sig { returns(String) }
  def cbsd_id; end

  sig { params(value: String).void }
  def cbsd_id=(value); end

  sig { void }
  def clear_bytes_threshold; end

  sig { void }
  def clear_carrier_pub_key; end

  sig { void }
  def clear_cbsd_id; end

  sig { void }
  def clear_hotspot_pubkey; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_subscriber_threshold; end

  sig { void }
  def clear_threshold_timestamp; end

  sig { returns(String) }
  def hotspot_pubkey; end

  sig { params(value: String).void }
  def hotspot_pubkey=(value); end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(Integer) }
  def subscriber_threshold; end

  sig { params(value: Integer).void }
  def subscriber_threshold=(value); end

  sig { returns(Integer) }
  def threshold_timestamp; end

  sig { params(value: Integer).void }
  def threshold_timestamp=(value); end
end
