# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_usage_carrier_transfer_info`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_usage_carrier_transfer_info`.


class Helium::PocMobile::Radio_usage_carrier_transfer_info < Google::Protobuf::AbstractMessage
  sig do
    params(
      carrier_id: T.nilable(T.any(Symbol, Integer)),
      transfer_bytes: T.nilable(Integer),
      user_count: T.nilable(Integer)
    ).void
  end
  def initialize(carrier_id: nil, transfer_bytes: nil, user_count: nil); end

  sig { returns(T.any(Symbol, Integer)) }
  def carrier_id; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def carrier_id=(value); end

  sig { void }
  def clear_carrier_id; end

  sig { void }
  def clear_transfer_bytes; end

  sig { void }
  def clear_user_count; end

  sig { returns(Integer) }
  def transfer_bytes; end

  sig { params(value: Integer).void }
  def transfer_bytes=(value); end

  sig { returns(Integer) }
  def user_count; end

  sig { params(value: Integer).void }
  def user_count=(value); end
end
