# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_reward_share`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_reward_share`.


class Helium::PocMobile::Radio_reward_share < Google::Protobuf::AbstractMessage
  sig do
    params(
      amount: T.nilable(Integer),
      cbsd_id: T.nilable(String),
      end_epoch: T.nilable(Integer),
      hotspot_key: T.nilable(String),
      owner_key: T.nilable(String),
      start_epoch: T.nilable(Integer)
    ).void
  end
  def initialize(amount: nil, cbsd_id: nil, end_epoch: nil, hotspot_key: nil, owner_key: nil, start_epoch: nil); end

  sig { returns(Integer) }
  def amount; end

  sig { params(value: Integer).void }
  def amount=(value); end

  sig { returns(String) }
  def cbsd_id; end

  sig { params(value: String).void }
  def cbsd_id=(value); end

  sig { void }
  def clear_amount; end

  sig { void }
  def clear_cbsd_id; end

  sig { void }
  def clear_end_epoch; end

  sig { void }
  def clear_hotspot_key; end

  sig { void }
  def clear_owner_key; end

  sig { void }
  def clear_start_epoch; end

  sig { returns(Integer) }
  def end_epoch; end

  sig { params(value: Integer).void }
  def end_epoch=(value); end

  sig { returns(String) }
  def hotspot_key; end

  sig { params(value: String).void }
  def hotspot_key=(value); end

  sig { returns(String) }
  def owner_key; end

  sig { params(value: String).void }
  def owner_key=(value); end

  sig { returns(Integer) }
  def start_epoch; end

  sig { params(value: Integer).void }
  def start_epoch=(value); end
end
