# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_reward`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_reward`.


class Helium::PocMobile::Radio_reward < Google::Protobuf::AbstractMessage
  sig do
    params(
      boosted_hexes: T.nilable(T.any(Google::Protobuf::RepeatedField[Helium::PocMobile::Boosted_hex], T::Array[Helium::PocMobile::Boosted_hex])),
      cbsd_id: T.nilable(String),
      coverage_object: T.nilable(String),
      coverage_points: T.nilable(Integer),
      dc_transfer_reward: T.nilable(Integer),
      hotspot_key: T.nilable(String),
      location_trust_score_multiplier: T.nilable(Integer),
      poc_reward: T.nilable(Integer),
      seniority_timestamp: T.nilable(Integer),
      speedtest_multiplier: T.nilable(Integer)
    ).void
  end
  def initialize(boosted_hexes: T.unsafe(nil), cbsd_id: nil, coverage_object: nil, coverage_points: nil, dc_transfer_reward: nil, hotspot_key: nil, location_trust_score_multiplier: nil, poc_reward: nil, seniority_timestamp: nil, speedtest_multiplier: nil); end

  sig { returns(Google::Protobuf::RepeatedField[Helium::PocMobile::Boosted_hex]) }
  def boosted_hexes; end

  sig { params(value: Google::Protobuf::RepeatedField[Helium::PocMobile::Boosted_hex]).void }
  def boosted_hexes=(value); end

  sig { returns(String) }
  def cbsd_id; end

  sig { params(value: String).void }
  def cbsd_id=(value); end

  sig { void }
  def clear_boosted_hexes; end

  sig { void }
  def clear_cbsd_id; end

  sig { void }
  def clear_coverage_object; end

  sig { void }
  def clear_coverage_points; end

  sig { void }
  def clear_dc_transfer_reward; end

  sig { void }
  def clear_hotspot_key; end

  sig { void }
  def clear_location_trust_score_multiplier; end

  sig { void }
  def clear_poc_reward; end

  sig { void }
  def clear_seniority_timestamp; end

  sig { void }
  def clear_speedtest_multiplier; end

  sig { returns(String) }
  def coverage_object; end

  sig { params(value: String).void }
  def coverage_object=(value); end

  sig { returns(Integer) }
  def coverage_points; end

  sig { params(value: Integer).void }
  def coverage_points=(value); end

  sig { returns(Integer) }
  def dc_transfer_reward; end

  sig { params(value: Integer).void }
  def dc_transfer_reward=(value); end

  sig { returns(String) }
  def hotspot_key; end

  sig { params(value: String).void }
  def hotspot_key=(value); end

  sig { returns(Integer) }
  def location_trust_score_multiplier; end

  sig { params(value: Integer).void }
  def location_trust_score_multiplier=(value); end

  sig { returns(Integer) }
  def poc_reward; end

  sig { params(value: Integer).void }
  def poc_reward=(value); end

  sig { returns(Integer) }
  def seniority_timestamp; end

  sig { params(value: Integer).void }
  def seniority_timestamp=(value); end

  sig { returns(Integer) }
  def speedtest_multiplier; end

  sig { params(value: Integer).void }
  def speedtest_multiplier=(value); end
end
