# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_hex_signal_level`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_hex_signal_level`.


class Helium::PocMobile::Radio_hex_signal_level < Google::Protobuf::AbstractMessage
  sig do
    params(
      location: T.nilable(String),
      signal_level: T.nilable(T.any(Symbol, Integer)),
      signal_power: T.untyped
    ).void
  end
  def initialize(location: nil, signal_level: nil, signal_power: nil); end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_signal_level; end

  sig { void }
  def clear_signal_power; end

  sig { returns(String) }
  def location; end

  sig { params(value: String).void }
  def location=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def signal_level; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def signal_level=(value); end

  sig { returns(T.untyped) }
  def signal_power; end

  sig { params(value: T.untyped).void }
  def signal_power=(value); end
end
