# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Seniority_update_reason`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Seniority_update_reason`.


module Helium::PocMobile::Seniority_update_reason
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Seniority_update_reason::seniority_update_reason_heartbeat_not_seen = 0
Helium::PocMobile::Seniority_update_reason::seniority_update_reason_new_coverage_claim_time = 1
Helium::PocMobile::Seniority_update_reason::seniority_update_reason_service_provider_ban = 2
