# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Signal_level`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Signal_level`.


module Helium::PocMobile::Signal_level
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Signal_level::HIGH = 3
Helium::PocMobile::Signal_level::LOW = 1
Helium::PocMobile::Signal_level::MEDIUM = 2
Helium::PocMobile::Signal_level::NONE = 0
