# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Sp_boosted_hex_status`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Sp_boosted_hex_status`.


module Helium::PocMobile::Sp_boosted_hex_status
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_average_asserted_distance_over_limit = 4
Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_eligible = 0
Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_location_score_below_threshold = 1
Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_not_enough_connections = 5
Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_radio_threshold_not_met = 2
Helium::PocMobile::Sp_boosted_hex_status::sp_boosted_hex_status_service_provider_ban = 3
