# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Speedtest`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Speedtest`.


class Helium::PocMobile::Speedtest < Google::Protobuf::AbstractMessage
  sig do
    params(
      download_speed_bps: T.nilable(Integer),
      latency_ms: T.nilable(Integer),
      timestamp: T.nilable(Integer),
      upload_speed_bps: T.nilable(Integer)
    ).void
  end
  def initialize(download_speed_bps: nil, latency_ms: nil, timestamp: nil, upload_speed_bps: nil); end

  sig { void }
  def clear_download_speed_bps; end

  sig { void }
  def clear_latency_ms; end

  sig { void }
  def clear_timestamp; end

  sig { void }
  def clear_upload_speed_bps; end

  sig { returns(Integer) }
  def download_speed_bps; end

  sig { params(value: Integer).void }
  def download_speed_bps=(value); end

  sig { returns(Integer) }
  def latency_ms; end

  sig { params(value: Integer).void }
  def latency_ms=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end

  sig { returns(Integer) }
  def upload_speed_bps; end

  sig { params(value: Integer).void }
  def upload_speed_bps=(value); end
end
