# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Speedtest_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Speedtest_req_v1`.


class Helium::PocMobile::Speedtest_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      download_speed: T.nilable(Integer),
      latency: T.nilable(Integer),
      pub_key: T.nilable(String),
      serial: T.nilable(String),
      signature: T.nilable(String),
      timestamp: T.nilable(Integer),
      upload_speed: T.nilable(Integer)
    ).void
  end
  def initialize(download_speed: nil, latency: nil, pub_key: nil, serial: nil, signature: nil, timestamp: nil, upload_speed: nil); end

  sig { void }
  def clear_download_speed; end

  sig { void }
  def clear_latency; end

  sig { void }
  def clear_pub_key; end

  sig { void }
  def clear_serial; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_timestamp; end

  sig { void }
  def clear_upload_speed; end

  sig { returns(Integer) }
  def download_speed; end

  sig { params(value: Integer).void }
  def download_speed=(value); end

  sig { returns(Integer) }
  def latency; end

  sig { params(value: Integer).void }
  def latency=(value); end

  sig { returns(String) }
  def pub_key; end

  sig { params(value: String).void }
  def pub_key=(value); end

  sig { returns(String) }
  def serial; end

  sig { params(value: String).void }
  def serial=(value); end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end

  sig { returns(Integer) }
  def upload_speed; end

  sig { params(value: Integer).void }
  def upload_speed=(value); end
end
