# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Subscriber_verified_mapping_event_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Subscriber_verified_mapping_event_req_v1`.


class Helium::PocMobile::Subscriber_verified_mapping_event_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      carrier_mapping_key: T.nilable(String),
      signature: T.nilable(String),
      subscriber_id: T.nilable(String),
      timestamp: T.nilable(Integer),
      total_reward_points: T.nilable(Integer)
    ).void
  end
  def initialize(carrier_mapping_key: nil, signature: nil, subscriber_id: nil, timestamp: nil, total_reward_points: nil); end

  sig { returns(String) }
  def carrier_mapping_key; end

  sig { params(value: String).void }
  def carrier_mapping_key=(value); end

  sig { void }
  def clear_carrier_mapping_key; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_subscriber_id; end

  sig { void }
  def clear_timestamp; end

  sig { void }
  def clear_total_reward_points; end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(String) }
  def subscriber_id; end

  sig { params(value: String).void }
  def subscriber_id=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end

  sig { returns(Integer) }
  def total_reward_points; end

  sig { params(value: Integer).void }
  def total_reward_points=(value); end
end
