# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Subscriber_verified_mapping_event_res_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Subscriber_verified_mapping_event_res_v1`.


class Helium::PocMobile::Subscriber_verified_mapping_event_res_v1 < Google::Protobuf::AbstractMessage
  sig { params(id: T.nilable(String)).void }
  def initialize(id: nil); end

  sig { void }
  def clear_id; end

  sig { returns(String) }
  def id; end

  sig { params(value: String).void }
  def id=(value); end
end
