# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Subscriber_mapping_activity_res_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Subscriber_mapping_activity_res_v1`.


class Helium::PocMobile::Subscriber_mapping_activity_res_v1 < Google::Protobuf::AbstractMessage
  sig { params(timestamp: T.nilable(Integer)).void }
  def initialize(timestamp: nil); end

  sig { void }
  def clear_timestamp; end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
