# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Subscriber_report_verification_status`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Subscriber_report_verification_status`.


module Helium::PocMobile::Subscriber_report_verification_status
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Subscriber_report_verification_status::invalid_carrier_key = 2
Helium::PocMobile::Subscriber_report_verification_status::invalid_reward_override_entity_key = 3
Helium::PocMobile::Subscriber_report_verification_status::invalid_subscriber_id = 1
Helium::PocMobile::Subscriber_report_verification_status::valid = 0
