# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Unallocated_reward`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Unallocated_reward`.


class Helium::PocMobile::Unallocated_reward < Google::Protobuf::AbstractMessage
  sig { params(amount: T.nilable(Integer), reward_type: T.nilable(T.any(Symbol, Integer))).void }
  def initialize(amount: nil, reward_type: nil); end

  sig { returns(Integer) }
  def amount; end

  sig { params(value: Integer).void }
  def amount=(value); end

  sig { void }
  def clear_amount; end

  sig { void }
  def clear_reward_type; end

  sig { returns(T.any(Symbol, Integer)) }
  def reward_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def reward_type=(value); end
end
