# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Unallocated_reward_type`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Unallocated_reward_type`.


module Helium::PocMobile::Unallocated_reward_type
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_data = 5
Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_discovery_location = 1
Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_mapper = 2
Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_oracle = 4
Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_poc = 0
Helium::PocMobile::Unallocated_reward_type::unallocated_reward_type_service_provider = 3
