# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Unban_details_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Unban_details_v1`.


class Helium::PocMobile::Unban_details_v1 < Google::Protobuf::AbstractMessage
  sig { params(hotspot_serial: T.nilable(String), message: T.nilable(String)).void }
  def initialize(hotspot_serial: nil, message: nil); end

  sig { void }
  def clear_hotspot_serial; end

  sig { void }
  def clear_message; end

  sig { returns(String) }
  def hotspot_serial; end

  sig { params(value: String).void }
  def hotspot_serial=(value); end

  sig { returns(String) }
  def message; end

  sig { params(value: String).void }
  def message=(value); end
end
