# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Verified_invalidated_radio_threshold_ingest_report_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Verified_invalidated_radio_threshold_ingest_report_v1`.


class Helium::PocMobile::Verified_invalidated_radio_threshold_ingest_report_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      report: T.nilable(Helium::PocMobile::Invalidated_radio_threshold_ingest_report_v1),
      status: T.nilable(T.any(Symbol, Integer)),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(report: nil, status: nil, timestamp: nil); end

  sig { void }
  def clear_report; end

  sig { void }
  def clear_status; end

  sig { void }
  def clear_timestamp; end

  sig { returns(Object) }
  def has_report?; end

  sig { returns(T.nilable(Helium::PocMobile::Invalidated_radio_threshold_ingest_report_v1)) }
  def report; end

  sig { params(value: T.nilable(Helium::PocMobile::Invalidated_radio_threshold_ingest_report_v1)).void }
  def report=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
