# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Wifi_heartbeat_req_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Wifi_heartbeat_req_v1`.


class Helium::PocMobile::Wifi_heartbeat_req_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      coverage_object: T.nilable(String),
      lat: T.nilable(Float),
      location_source: T.nilable(T.any(Symbol, Integer)),
      location_validation_timestamp: T.nilable(Integer),
      lon: T.nilable(Float),
      operation_mode: T.nilable(T::Boolean),
      pub_key: T.nilable(String),
      signature: T.nilable(String),
      timestamp: T.nilable(Integer)
    ).void
  end
  def initialize(coverage_object: nil, lat: nil, location_source: nil, location_validation_timestamp: nil, lon: nil, operation_mode: nil, pub_key: nil, signature: nil, timestamp: nil); end

  sig { void }
  def clear_coverage_object; end

  sig { void }
  def clear_lat; end

  sig { void }
  def clear_location_source; end

  sig { void }
  def clear_location_validation_timestamp; end

  sig { void }
  def clear_lon; end

  sig { void }
  def clear_operation_mode; end

  sig { void }
  def clear_pub_key; end

  sig { void }
  def clear_signature; end

  sig { void }
  def clear_timestamp; end

  sig { returns(String) }
  def coverage_object; end

  sig { params(value: String).void }
  def coverage_object=(value); end

  sig { returns(Float) }
  def lat; end

  sig { params(value: Float).void }
  def lat=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def location_source; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def location_source=(value); end

  sig { returns(Integer) }
  def location_validation_timestamp; end

  sig { params(value: Integer).void }
  def location_validation_timestamp=(value); end

  sig { returns(Float) }
  def lon; end

  sig { params(value: Float).void }
  def lon=(value); end

  sig { returns(T::Boolean) }
  def operation_mode; end

  sig { params(value: T::Boolean).void }
  def operation_mode=(value); end

  sig { returns(String) }
  def pub_key; end

  sig { params(value: String).void }
  def pub_key=(value); end

  sig { returns(String) }
  def signature; end

  sig { params(value: String).void }
  def signature=(value); end

  sig { returns(Integer) }
  def timestamp; end

  sig { params(value: Integer).void }
  def timestamp=(value); end
end
