# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Service_provider_boosted_rewards_banned_radio_req_v1::Sp_boosted_rewards_banned_radio_ban_type`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Service_provider_boosted_rewards_banned_radio_req_v1::Sp_boosted_rewards_banned_radio_ban_type`.


module Helium::PocMobile::Service_provider_boosted_rewards_banned_radio_req_v1::Sp_boosted_rewards_banned_radio_ban_type
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Service_provider_boosted_rewards_banned_radio_req_v1::Sp_boosted_rewards_banned_radio_ban_type::boosted_hex = 0
Helium::PocMobile::Service_provider_boosted_rewards_banned_radio_req_v1::Sp_boosted_rewards_banned_radio_ban_type::poc = 1
