# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status`.


module Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status::duplicate = 3
Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status::invalid_gateway_key = 1
Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status::invalid_routing_key = 2
Helium::PocMobile::Verified_data_transfer_ingest_report_v1::Report_status::valid = 0
