# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::Decimal`.
# Please instead update this file by running `bin/tapioca dsl Helium::Decimal`.


class Helium::Decimal < Google::Protobuf::AbstractMessage
  sig { params(value: T.nilable(String)).void }
  def initialize(value: nil); end

  sig { void }
  def clear_value; end

  sig { returns(String) }
  def value; end

  sig { params(value: String).void }
  def value=(value); end
end
