# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocMobile::Radio_reward_v2::Location_trust_score`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocMobile::Radio_reward_v2::Location_trust_score`.


class Helium::PocMobile::Radio_reward_v2::Location_trust_score < Google::Protobuf::AbstractMessage
  sig { params(meters_to_asserted: T.nilable(Integer), trust_score: T.nilable(Helium::Decimal)).void }
  def initialize(meters_to_asserted: nil, trust_score: nil); end

  sig { void }
  def clear_meters_to_asserted; end

  sig { void }
  def clear_trust_score; end

  sig { returns(Object) }
  def has_trust_score?; end

  sig { returns(Integer) }
  def meters_to_asserted; end

  sig { params(value: Integer).void }
  def meters_to_asserted=(value); end

  sig { returns(T.nilable(Helium::Decimal)) }
  def trust_score; end

  sig { params(value: T.nilable(Helium::Decimal)).void }
  def trust_score=(value); end
end
