# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Invalid_details`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Invalid_details`.


class Helium::PocLora::Invalid_details < Google::Protobuf::AbstractMessage
  sig { params(denylist_tag: T.nilable(String)).void }
  def initialize(denylist_tag: nil); end

  sig { void }
  def clear_denylist_tag; end

  sig { returns(T.nilable(Symbol)) }
  def data; end

  sig { returns(String) }
  def denylist_tag; end

  sig { params(value: String).void }
  def denylist_tag=(value); end

  sig { returns(Object) }
  def has_denylist_tag?; end
end
