# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Lora_stream_session_offer_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Lora_stream_session_offer_v1`.


class Helium::PocLora::Lora_stream_session_offer_v1 < Google::Protobuf::AbstractMessage
  sig { params(nonce: T.nilable(String)).void }
  def initialize(nonce: nil); end

  sig { void }
  def clear_nonce; end

  sig { returns(String) }
  def nonce; end

  sig { params(value: String).void }
  def nonce=(value); end
end
