# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Lora_valid_beacon_report_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Lora_valid_beacon_report_v1`.


class Helium::PocLora::Lora_valid_beacon_report_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      elevation: T.nilable(Integer),
      gain: T.nilable(Integer),
      hex_scale: T.nilable(Integer),
      location: T.nilable(String),
      received_timestamp: T.nilable(Integer),
      report: T.nilable(Helium::PocLora::Lora_beacon_report_req_v1),
      reward_unit: T.nilable(Integer)
    ).void
  end
  def initialize(elevation: nil, gain: nil, hex_scale: nil, location: nil, received_timestamp: nil, report: nil, reward_unit: nil); end

  sig { void }
  def clear_elevation; end

  sig { void }
  def clear_gain; end

  sig { void }
  def clear_hex_scale; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_received_timestamp; end

  sig { void }
  def clear_report; end

  sig { void }
  def clear_reward_unit; end

  sig { returns(Integer) }
  def elevation; end

  sig { params(value: Integer).void }
  def elevation=(value); end

  sig { returns(Integer) }
  def gain; end

  sig { params(value: Integer).void }
  def gain=(value); end

  sig { returns(Object) }
  def has_report?; end

  sig { returns(Integer) }
  def hex_scale; end

  sig { params(value: Integer).void }
  def hex_scale=(value); end

  sig { returns(String) }
  def location; end

  sig { params(value: String).void }
  def location=(value); end

  sig { returns(Integer) }
  def received_timestamp; end

  sig { params(value: Integer).void }
  def received_timestamp=(value); end

  sig { returns(T.nilable(Helium::PocLora::Lora_beacon_report_req_v1)) }
  def report; end

  sig { params(value: T.nilable(Helium::PocLora::Lora_beacon_report_req_v1)).void }
  def report=(value); end

  sig { returns(Integer) }
  def reward_unit; end

  sig { params(value: Integer).void }
  def reward_unit=(value); end
end
