# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Lora_verified_witness_report_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Lora_verified_witness_report_v1`.


class Helium::PocLora::Lora_verified_witness_report_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      elevation: T.nilable(Integer),
      gain: T.nilable(Integer),
      hex_scale: T.nilable(Integer),
      invalid_details: T.nilable(Helium::PocLora::Invalid_details),
      invalid_reason: T.nilable(T.any(Symbol, Integer)),
      location: T.nilable(String),
      participant_side: T.nilable(T.any(Symbol, Integer)),
      received_timestamp: T.nilable(Integer),
      report: T.nilable(Helium::PocLora::Lora_witness_report_req_v1),
      reward_unit: T.nilable(Integer),
      status: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(elevation: nil, gain: nil, hex_scale: nil, invalid_details: nil, invalid_reason: nil, location: nil, participant_side: nil, received_timestamp: nil, report: nil, reward_unit: nil, status: nil); end

  sig { void }
  def clear_elevation; end

  sig { void }
  def clear_gain; end

  sig { void }
  def clear_hex_scale; end

  sig { void }
  def clear_invalid_details; end

  sig { void }
  def clear_invalid_reason; end

  sig { void }
  def clear_location; end

  sig { void }
  def clear_participant_side; end

  sig { void }
  def clear_received_timestamp; end

  sig { void }
  def clear_report; end

  sig { void }
  def clear_reward_unit; end

  sig { void }
  def clear_status; end

  sig { returns(Integer) }
  def elevation; end

  sig { params(value: Integer).void }
  def elevation=(value); end

  sig { returns(Integer) }
  def gain; end

  sig { params(value: Integer).void }
  def gain=(value); end

  sig { returns(Object) }
  def has_invalid_details?; end

  sig { returns(Object) }
  def has_report?; end

  sig { returns(Integer) }
  def hex_scale; end

  sig { params(value: Integer).void }
  def hex_scale=(value); end

  sig { returns(T.nilable(Helium::PocLora::Invalid_details)) }
  def invalid_details; end

  sig { params(value: T.nilable(Helium::PocLora::Invalid_details)).void }
  def invalid_details=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def invalid_reason; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def invalid_reason=(value); end

  sig { returns(String) }
  def location; end

  sig { params(value: String).void }
  def location=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def participant_side; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def participant_side=(value); end

  sig { returns(Integer) }
  def received_timestamp; end

  sig { params(value: Integer).void }
  def received_timestamp=(value); end

  sig { returns(T.nilable(Helium::PocLora::Lora_witness_report_req_v1)) }
  def report; end

  sig { params(value: T.nilable(Helium::PocLora::Lora_witness_report_req_v1)).void }
  def report=(value); end

  sig { returns(Integer) }
  def reward_unit; end

  sig { params(value: Integer).void }
  def reward_unit=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def status; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def status=(value); end
end
