# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Lora_invalid_witness_report_v1`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Lora_invalid_witness_report_v1`.


class Helium::PocLora::Lora_invalid_witness_report_v1 < Google::Protobuf::AbstractMessage
  sig do
    params(
      invalid_details: T.nilable(Helium::PocLora::Invalid_details),
      participant_side: T.nilable(T.any(Symbol, Integer)),
      reason: T.nilable(T.any(Symbol, Integer)),
      received_timestamp: T.nilable(Integer),
      report: T.nilable(Helium::PocLora::Lora_witness_report_req_v1)
    ).void
  end
  def initialize(invalid_details: nil, participant_side: nil, reason: nil, received_timestamp: nil, report: nil); end

  sig { void }
  def clear_invalid_details; end

  sig { void }
  def clear_participant_side; end

  sig { void }
  def clear_reason; end

  sig { void }
  def clear_received_timestamp; end

  sig { void }
  def clear_report; end

  sig { returns(Object) }
  def has_invalid_details?; end

  sig { returns(Object) }
  def has_report?; end

  sig { returns(T.nilable(Helium::PocLora::Invalid_details)) }
  def invalid_details; end

  sig { params(value: T.nilable(Helium::PocLora::Invalid_details)).void }
  def invalid_details=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def participant_side; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def participant_side=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def reason; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def reason=(value); end

  sig { returns(Integer) }
  def received_timestamp; end

  sig { params(value: Integer).void }
  def received_timestamp=(value); end

  sig { returns(T.nilable(Helium::PocLora::Lora_witness_report_req_v1)) }
  def report; end

  sig { params(value: T.nilable(Helium::PocLora::Lora_witness_report_req_v1)).void }
  def report=(value); end
end
