# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Non_rewardable_packet_reason`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Non_rewardable_packet_reason`.


module Helium::PocLora::Non_rewardable_packet_reason
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocLora::Non_rewardable_packet_reason::gateway_not_found_for_packet = 0
