# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PocLora::Verification_status`.
# Please instead update this file by running `bin/tapioca dsl Helium::PocLora::Verification_status`.


module Helium::PocLora::Verification_status
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Helium::PocLora::Verification_status::invalid = 1
Helium::PocLora::Verification_status::valid = 0
