# syntax=docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.1
FROM docker.io/library/ruby:$RUBY_VERSION

# Install dependencies
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  pkg-config \
  curl \
  libpq5 \
  postgresql-client \
  libsodium-dev \
  cmake && \
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Install latest protobuf compiler
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v30.0/protoc-30.0-linux-x86_64.zip && \
  apt-get update -qq && \
  apt-get install -y unzip && \
  unzip protoc-30.0-linux-x86_64.zip -d /usr/local && \
  rm protoc-30.0-linux-x86_64.zip && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Set up application
WORKDIR /app

# Set Sidekiq Pro Bundler credentials
ARG BUNDLE_GEMS__CONTRIBSYS__COM
ENV BUNDLE_GEMS__CONTRIBSYS__COM=${BUNDLE_GEMS__CONTRIBSYS__COM}

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs "$(nproc)" --retry 3

# Copy application code
COPY . .

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/dev"]
