source "https://rubygems.org"

# Ruby on Rails
gem "rails", "~> 8.0.1"

# Web infrastructure
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "thruster", require: false

# ActiveRecord
gem "pg", "~> 1.1"
gem "activerecord-import"

# ActiveJob
source "https://gems.contribsys.com/" do
  gem "sidekiq-pro"
end
gem "redis", group: :production
gem "clockwork", require: false

# Frontend
gem "propshaft"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "view_component"
gem "simple_form"

# Authentication
gem "devise"

# Type checking
gem "sorbet", group: :development
gem "sorbet-runtime"
gem "sorbet-rails"
gem "spoom", group: :development
gem "tapioca", require: false, group: :development # For generating RBI files
gem "zeitwerk", "2.7.2" # https://github.com/Shopify/tapioca/issues/2281

# REST
gem "blueprinter"
gem "blueprinter-activerecord"
gem "kaminari"

# AWS
gem "aws-sdk-s3"

# OpenStruct
gem "ostruct"

# L2 Helium data
gem "google-protobuf"
gem "zlib"

# Sentry
gem "sentry-ruby"
gem "sentry-rails"
gem "stackprof"

# Analytics
gem "posthog-ruby"

group :development, :test do
  # Debugging
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  # Static analysis
  gem "brakeman", require: false
  gem "rubocop", require: false
  gem "rubocop-sorbet", require: false
  gem "rubocop-rails-omakase", require: false

  # Testing
  gem "rspec-rails"
  gem "capybara"
  gem "selenium-webdriver"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-sorbet"
end
