name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Run Brakeman
        run: docker compose run --rm --no-deps web bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Audit JS dependencies
        run: docker compose run --rm --no-deps web bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Run Rubocop
        run: docker compose run --rm --no-deps web bin/rubocop -f github

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Run Sorbet
        run: docker compose run --rm --no-deps web bundle exec spoom srb tc

  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
      REDIS_URL: redis://localhost:6379/1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy environment file
        run: cp .env.ci .env

      - name: Prepare the database
        run: docker compose run --rm web bundle exec rails db:prepare

      - name: Run RSpec
        run: docker compose run --rm web bundle exec rspec

  deploy:
    needs: [scan_ruby, scan_js, lint, typecheck, test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: us-east-1
      TF_VAR_app_name: rails-app
      TF_VAR_environment: production
      TF_VAR_domain_name: relay-helium-api.alessandro.codes
      TF_VAR_from_address: noreply@relay-helium-api.alessandro.codes
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_secret_key_base: ${{ secrets.TF_VAR_SECRET_KEY_BASE }}
      TF_VAR_devise_pepper: ${{ secrets.TF_VAR_DEVISE_PEPPER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploy to ECS
        run: bin/deploy
