# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Helium::PacketVerifier::Valid_packet`.
# Please instead update this file by running `bin/tapioca dsl Helium::PacketVerifier::Valid_packet`.


class Helium::PacketVerifier::Valid_packet < Google::Protobuf::AbstractMessage
  sig do
    params(
      gateway: T.nilable(String),
      num_dcs: T.nilable(Integer),
      packet_timestamp: T.nilable(Integer),
      payload_hash: T.nilable(String),
      payload_size: T.nilable(Integer)
    ).void
  end
  def initialize(gateway: nil, num_dcs: nil, packet_timestamp: nil, payload_hash: nil, payload_size: nil); end

  sig { void }
  def clear_gateway; end

  sig { void }
  def clear_num_dcs; end

  sig { void }
  def clear_packet_timestamp; end

  sig { void }
  def clear_payload_hash; end

  sig { void }
  def clear_payload_size; end

  sig { returns(String) }
  def gateway; end

  sig { params(value: String).void }
  def gateway=(value); end

  sig { returns(Integer) }
  def num_dcs; end

  sig { params(value: Integer).void }
  def num_dcs=(value); end

  sig { returns(Integer) }
  def packet_timestamp; end

  sig { params(value: Integer).void }
  def packet_timestamp=(value); end

  sig { returns(String) }
  def payload_hash; end

  sig { params(value: String).void }
  def payload_hash=(value); end

  sig { returns(Integer) }
  def payload_size; end

  sig { params(value: Integer).void }
  def payload_size=(value); end
end
